spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: utf-8
      enabled: true
server:
  port: 8090
  servlet:
    context-path: /center